### ISSUE TITLE
unhandled event error if using Ember.data

### ISSUE THREAD

**Issue by wyaeld** [ghempton/ember-layout#1]
Discovered that when ember-layout + ember-routemanager are combined with ember-data, you get a 'setData' event being dispatched by the RESTadapter that seems to hit one of the RouteManagers LayoutStates.  This causes an error.

The particular event is occuring because in the enter() function for the state, I'm calling find on the datastore, which returns the model record it has immediately, and then dispatches an ajax request for updated information, which triggers a callback when it comes back.

Unfortunately I don't have a simple demo available of the problem, but let me know if you need more to go on, or can see why this is happening

**Comment by ghempton** [comment]
Is there any chance you could create a jsfiddle?

**Comment by wyaeld** [comment]
Not sure how to do a jsfiddle that requires ember-data and a restful
backend to work.  I can possibly put up a public clone of the affected
codebase so you can see the part that causes the problem.

On Tue, Feb 21, 2012 at 6:37 AM, Gordon L. Hempton <
reply@reply.github.com

**Comment by wyaeld** [comment]
Apologies Gordon, the problem isn't actually caused by your Ember.Layout, its purely Ember.Data itself.

The sequence is

``` javascript
App = Ember.Application.create
  ready: ->
    @_super
    App.peopleController.findAll()

App.routeManager = Ember.RouteManager.create
  show: Ember.LayoutState.create
    path: 'people/:id'
    viewClass: App.PersonShowView
    enter: (stateManager, transition) ->
      @_super(stateManager, transition)
      App.personController.loadPerson(stateManager.params.id)

App.personController = Ember.Object.create

  loadPerson: (id) ->
    person = App.Store.find(App.Person, id)
```

With Ember.Data plugged in, the Application has already loaded the Person objects in the ready() callback.  The find returns the client side store object and fires an ajax request.  The Person is already loaded when the ajax success callback arrives (since the person was already loaded before the find() was called) and the 'saved' state does not handle the setData event triggered by the Ajax load.

**Comment by ghempton** [comment]
No worries. Thanks for looking into this.
