### ISSUE TITLE
One of the assertions is not asserting

### ISSUE THREAD

**Issue by bradleypriest** [ghempton/ember-layout#3]
Hi, I noticed https://github.com/ghempton/ember-layout/blob/master/packages/ember-layout/lib/helpers/dynamic_view.js#L39 the I think the assertion is back to front.

However fixing it breaks the example app (couldn't get tests running).
Thoughts?

**Comment by lcoq** [comment]
I'm not sure, but don't you should use Ember.View.detect instead of "instanceOf"?
